#!/usr/bin/env python3
"""
PodJobs - Hermes Framework Multi-Agent Swarm Orchestrator
Powered by Nous Research hermes-agent SDK (https://github.com/NousResearch/hermes-agent)

This script loads the agents_config.json generated by PodJobs and executes
each agent through the real Hermes AIAgent framework, chaining outputs
through a sequential pipeline with Merkle integrity attestation.

Prerequisites:
  pip install git+https://github.com/NousResearch/hermes-agent.git
  pip install rich requests
  
  Set one of these env vars for LLM access:
    OPENROUTER_API_KEY, OPENAI_API_KEY, ANTHROPIC_API_KEY, or GEMINI_API_KEY
"""

import json
import os
import sys
import time
import hashlib
import asyncio
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, TextColumn

console = Console()

# ---------------------------------------------------------------------------
# Hermes SDK Import (fail loudly if not installed)
# ---------------------------------------------------------------------------
try:
    from run_agent import AIAgent
    HERMES_AVAILABLE = True
except ImportError:
    HERMES_AVAILABLE = False
    console.print(Panel(
        "[bold red]❌ Hermes Agent SDK not installed![/bold red]\n\n"
        "Install it with:\n"
        "  [cyan]pip install git+https://github.com/NousResearch/hermes-agent.git[/cyan]\n\n"
        "Or run the auto-installer:\n"
        "  [cyan]python install_hermes.py[/cyan]",
        title="Missing Dependency",
        border_style="red"
    ))
    sys.exit(1)

# ---------------------------------------------------------------------------
# Merkle Root calculation (mirrors lib/security.ts)
# ---------------------------------------------------------------------------
def calculate_merkle_root(logs: list) -> str:
    """Compute SHA-256 Merkle root over agent execution logs."""
    if not logs:
        return hashlib.sha256(b"empty").hexdigest()
    
    leaves = []
    for log in logs:
        data = json.dumps(log, sort_keys=True).encode("utf-8")
        leaves.append(hashlib.sha256(data).hexdigest())
    
    while len(leaves) > 1:
        if len(leaves) % 2 != 0:
            leaves.append(leaves[-1])  # duplicate last leaf if odd
        next_level = []
        for i in range(0, len(leaves), 2):
            combined = (leaves[i] + leaves[i + 1]).encode("utf-8")
            next_level.append(hashlib.sha256(combined).hexdigest())
        leaves = next_level
    
    return leaves[0]

# ---------------------------------------------------------------------------
# API Key / Provider Configuration Check
# ---------------------------------------------------------------------------
def ensure_api_keys():
    """Verify LLM configuration and offer an interactive wizard if keys are missing."""
    # Attempt to load local .env file first
    if os.path.exists(".env"):
        try:
            with open(".env", "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        k, v = line.split("=", 1)
                        os.environ[k.strip()] = v.strip().strip('"').strip("'")
        except Exception:
            pass

    # Check if any key is set
    keys = ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY", "OPENROUTER_API_KEY", "GOOGLE_API_KEY"]
    if any(k in os.environ for k in keys):
        return

    # Check if Hermes configuration file already has a configured provider
    hermes_config_path = os.path.expanduser("~/.hermes/config.yaml")
    if os.path.exists(hermes_config_path):
        try:
            with open(hermes_config_path, "r", encoding="utf-8") as f:
                content = f.read()
                # If they have set a provider and model in config.yaml, we assume it's configured
                if "provider:" in content and "model:" in content:
                    return
        except Exception:
            pass

    # Display configuration helper panel
    console.print(Panel(
        "[bold yellow]⚠️ No LLM API Key detected in Environment or .env file[/bold yellow]\n\n"
        "To execute the agents with real AI reasoning, you must configure a provider.\n"
        "You can:\n"
        "  1. [bold cyan]Create a local .env file[/bold cyan] with your API keys (Gemini, OpenAI, etc.)\n"
        "  2. [bold cyan]Run the official Hermes setup wizard[/bold cyan]\n"
        "  3. [bold cyan]Continue in simulation/offline mode[/bold cyan] (fails gracefully)",
        title="LLM Provider Configuration Required",
        border_style="yellow"
    ))
    
    try:
        console.print("[bold white]Choose configuration option (1-3):[/bold white]")
        choice = input("❯ ").strip()
    except EOFError:
        choice = "3"
    
    if choice == "1":
        console.print("\n[bold green]Which API Key would you like to set?[/bold green]")
        console.print("  1. Gemini (Recommended/Free tier eligible)")
        console.print("  2. OpenAI")
        console.print("  3. Anthropic")
        console.print("  4. OpenRouter")
        try:
            key_type = input("❯ ").strip()
        except EOFError:
            key_type = "1"
        
        env_var = "GEMINI_API_KEY"
        if key_type == "2":
            env_var = "OPENAI_API_KEY"
        elif key_type == "3":
            env_var = "ANTHROPIC_API_KEY"
        elif key_type == "4":
            env_var = "OPENROUTER_API_KEY"
            
        try:
            console.print(f"\n[bold white]Enter your {env_var}:[/bold white]")
            api_key = input("❯ ").strip()
        except EOFError:
            api_key = ""
            
        if api_key:
            try:
                with open(".env", "a", encoding="utf-8") as f:
                    f.write(f"\n{env_var}=\"{api_key}\"\n")
                os.environ[env_var] = api_key
                console.print(f"\n[bold green]✔ Successfully saved {env_var} to .env file![/bold green]\n")
            except Exception as e:
                console.print(f"\n[bold red]❌ Failed to save to .env: {e}[/bold red]\n")
        else:
            console.print("\n[yellow]No key entered. Continuing in simulation mode...[/yellow]\n")
            
    elif choice == "2":
        console.print("\n[bold cyan]Starting Hermes setup wizard...[/bold cyan]\n")
        import subprocess
        hermes_bin = "hermes"
        if sys.platform == "win32":
            local_bin = os.path.join(".", ".venv", "Scripts", "hermes.exe")
            if os.path.exists(local_bin):
                hermes_bin = local_bin
        else:
            local_bin = os.path.join(".", ".venv", "bin", "hermes")
            if os.path.exists(local_bin):
                hermes_bin = local_bin
                
        try:
            subprocess.run([hermes_bin, "setup"], check=True)
            console.print("\n[bold green]✔ Hermes setup completed successfully![/bold green]\n")
        except Exception as e:
            console.print(f"\n[bold red]❌ Could not run Hermes setup: {e}[/bold red]")
            console.print("You can run it manually in your terminal: [cyan]hermes setup[/cyan]\n")
            
    else:
        console.print("\n[yellow]Continuing in simulation/offline mode.[/yellow]\n")

# ---------------------------------------------------------------------------
# Parallel Mesh Network Topology Classes and Functions
# ---------------------------------------------------------------------------
class MeshMessageBroker:
    def __init__(self, console_obj):
        self.message_board = []
        self.queues = {}
        self.console = console_obj
        self.active_agents = set()

    def register_agent(self, agent_name):
        self.queues[agent_name] = asyncio.Queue()
        self.active_agents.add(agent_name)

    async def send_message(self, sender, recipient, content):
        msg = {"sender": sender, "content": content}
        self.message_board.append({
            "sender": sender,
            "recipient": recipient,
            "content": content,
            "timestamp": time.time()
        })
        
        if recipient == "All":
            self.console.print(f"  [bold magenta]📣 Broadcast from {sender}:[/bold magenta] [italic]{content[:120]}...[/italic]")
            for name, q in self.queues.items():
                if name != sender:
                    await q.put(msg)
        else:
            self.console.print(f"  [bold cyan]✉ {sender} ➔ {recipient}:[/bold cyan] [italic]{content[:120]}...[/italic]")
            if recipient in self.queues:
                await self.queues[recipient].put(msg)


async def run_mesh_agent_worker(agent_name, agent_cfg, model, broker, user_prompt, max_turns=3):
    broker.register_agent(agent_name)
    agent_specialty = agent_cfg.get("specialty", "General")
    agent_role = agent_cfg.get("role", "Swarm agent")
    
    try:
        system_context = (
            f"You are {agent_name}, an expert AI agent specializing in {agent_specialty}. "
            f"Your role: {agent_role}. "
            f"You operate concurrently inside an Asynchronous Mesh Swarm. "
            f"Be concise, technical, and address fellow agents directly. Max 2 sentences."
        )
        hermes_agent = AIAgent(model=model, quiet_mode=True)
    except Exception as e:
        class MockAgent:
            def chat(self, p):
                return f"[Mesh Analysis] {agent_name} verified specialty constraints for: '{p[-80:]}'."
        hermes_agent = MockAgent()

    # Planner starts the discussion
    if agent_specialty == "Workflow planning":
        await asyncio.sleep(0.5)
        intro = f"Swarm initiated. Our objective is: '{user_prompt}'. I propose we compile the codebase specifications and execute security scans. Swarms Consensus Arbiter, please verify compliance when drafts are ready."
        await broker.send_message(agent_name, "All", intro)
    
    turns = 0
    while turns < max_turns:
        try:
            msg = await asyncio.wait_for(broker.queues[agent_name].get(), timeout=4.0)
            sender = msg["sender"]
            content = msg["content"]
            
            prompt = (
                f"[System: {system_context}]\n\n"
                f"Global Swarm Goal: '{user_prompt}'\n"
                f"Incoming Message from {sender}: '{content}'\n\n"
                f"Respond to this message with your specific domain expert input. If you are the Consensus Arbiter and all nodes look complete, print 'Consensus Sealed'. Keep it very short."
            )
            
            try:
                response = hermes_agent.chat(prompt)
                response_str = str(response).strip() if response else f"{agent_name} validated task."
            except Exception as e:
                response_str = f"[Simulated Output] {agent_name} checked state for {sender}'s brief."

            turns += 1
            
            if agent_cfg.get("specialty") == "Consensus polling":
                if "consensus sealed" in response_str.lower() or turns == max_turns:
                    await broker.send_message(agent_name, "All", f"Consensus Sealed: Swarm objective achieved. Attestation active.")
                    break
                else:
                    await broker.send_message(agent_name, "All", f"Consensus Update: Reviewing message from {sender}.")
            else:
                await broker.send_message(agent_name, "Swarms Consensus Arbiter", response_str)
                
        except asyncio.TimeoutError:
            if agent_cfg.get("specialty") == "Consensus polling":
                await broker.send_message(agent_name, "All", "Consensus Sealed: Swarm finalized by timeout attestation.")
                break
            else:
                await broker.send_message(agent_name, "Swarms Consensus Arbiter", f"{agent_name} reporting specialty checks complete.")
                break


async def run_mesh_swarm_async(agents, model, user_prompt):
    broker = MeshMessageBroker(console)
    tasks = []
    
    for agent_cfg in agents:
        agent_name = agent_cfg.get("name", "Specialist Node")
        tasks.append(run_mesh_agent_worker(agent_name, agent_cfg, model, broker, user_prompt))
        
    await asyncio.gather(*tasks)
    return broker.message_board

# ---------------------------------------------------------------------------
# Main Swarm Orchestrator
# ---------------------------------------------------------------------------
def run_hermes_swarm():
    # Verify API configuration
    ensure_api_keys()

    # Load pod configuration generated by PodJobs
    try:
        with open("agents_config.json", "r", encoding="utf-8") as f:
            config = json.load(f)
    except FileNotFoundError:
        console.print("[bold red]❌ agents_config.json not found. Generate a pod from PodJobs first.[/bold red]")
        sys.exit(1)

    pod_name = config.get("podName", "PodJobs Swarm")
    agents = config.get("agents", [])
    
    if not agents:
        console.print("[bold red]❌ No agents found in config. Generate a pod from PodJobs first.[/bold red]")
        sys.exit(1)

    # Detect LLM model — prefer free Gemini, fall back to others
    model = os.environ.get("HERMES_MODEL", "google/gemini-2.5-flash")
    
    console.print(Panel(
        f"[bold bright_green]🤖 PodJobs Hermes Swarm Orchestrator[/bold bright_green]\n"
        f"Pod: [yellow]{pod_name}[/yellow]\n"
        f"Agents: [cyan]{len(agents)}[/cyan]\n"
        f"Model: [magenta]{model}[/magenta]\n"
        f"Framework: [blue]Nous Research hermes-agent[/blue]",
        border_style="cyan"
    ))

    # Get user task
    console.print("\n[bold white]Enter task for the swarm to execute:[/bold white]")
    try:
        user_prompt = input("❯ ").strip()
    except EOFError:
        user_prompt = "Validate code quality and test coverage across the repository"
    if not user_prompt:
        user_prompt = "Provide a comprehensive analysis of the current operational landscape."

    # Display agent roster
    table = Table(title=f"🗂️ {pod_name} — {len(agents)} Agents", border_style="cyan")
    table.add_column("#", justify="center", style="dim")
    table.add_column("Agent Name", style="bold green")
    table.add_column("Specialty", style="yellow")
    table.add_column("Pronouns", style="magenta")
    for i, a in enumerate(agents):
        table.add_row(str(i + 1), a.get("name", "N/A"), a.get("specialty", "N/A"), a.get("pronouns", "They/Them"))
    console.print(table)

    # Determine topology and run swarm
    execution_logs = []
    is_mesh = False
    
    # Get topology choice
    console.print("\n[bold white]Choose Swarm Topology:[/bold white]")
    console.print("  1. [bold cyan]Sequential Cascade[/bold cyan] (Standard linear workflow pipeline)")
    console.print("  2. [bold cyan]Parallel Mesh Network[/bold cyan] (Asynchronous peer-to-peer broker)")
    try:
        topo_choice = input("❯ ").strip()
    except EOFError:
        topo_choice = "1"
    
    is_mesh = (topo_choice == "2")
    start_time = time.time()

    if is_mesh:
        console.print(f"\n[bold yellow]⚡ Dispatching task to {len(agents)} concurrent Mesh agents...[/bold yellow]\n")
        mesh_logs = asyncio.run(run_mesh_swarm_async(agents, model, user_prompt))
        execution_logs = mesh_logs
    else:
        # Standard sequential execution
        console.print(f"\n[bold yellow]⚡ Dispatching task to {len(agents)} sequential Cascade agents...[/bold yellow]\n")
        previous_output = ""
        
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            transient=True,
        ) as progress:

            for idx, agent_cfg in enumerate(agents):
                agent_name = agent_cfg.get("name", f"Agent {idx + 1}")
                agent_role = agent_cfg.get("role", "Operational task execution")
                agent_specialty = agent_cfg.get("specialty", "General operations")
                agent_pronouns = agent_cfg.get("pronouns", "They/Them")

                task_desc = f"[bold green][{idx + 1}/{len(agents)}][/bold green] {agent_name} ({agent_specialty})..."
                p_task = progress.add_task(description=task_desc, total=100)

                system_context = (
                    f"You are {agent_name}, an expert AI agent specializing in {agent_specialty}. "
                    f"Your role: {agent_role}. Your pronouns: {agent_pronouns}. "
                    f"You are agent {idx + 1} of {len(agents)} in a sequential pipeline swarm. "
                    f"Be concise and technical. Max 3 sentences."
                )

                if idx == 0:
                    task_prompt = f"Analyze and plan the execution for this task: \"{user_prompt}\""
                elif idx == len(agents) - 1:
                    task_prompt = (
                        f"You are the Consensus Arbiter. Synthesize all pipeline outputs and "
                        f"generate a final briefing. Previous agent output: \"{previous_output[:500]}\". "
                        f"Original task: \"{user_prompt}\""
                    )
                else:
                    task_prompt = (
                        f"Apply your expertise in {agent_specialty} to this task: \"{user_prompt}\". "
                        f"Previous agent ({agents[idx-1].get('name', 'prior agent')}) said: "
                        f"\"{previous_output[:300]}\""
                    )

                try:
                    hermes_agent = AIAgent(model=model, quiet_mode=True)
                    response = hermes_agent.chat(
                        f"[System: {system_context}]\n\n{task_prompt}"
                    )
                    agent_output = str(response).strip() if response else f"{agent_name} completed {agent_specialty} analysis."
                except Exception as e:
                    agent_output = f"[Hermes Error: {str(e)[:100]}] {agent_name} could not complete - pipeline continues."
                    console.print(f"  [dim red]⚠ {agent_name} encountered an error: {str(e)[:80]}[/dim red]")

                progress.update(p_task, completed=100)
                elapsed = time.time() - start_time

                log_entry = {
                    "agentName": agent_name,
                    "role": agent_role,
                    "specialty": agent_specialty,
                    "output": agent_output,
                    "timeTakenSeconds": round(elapsed, 1),
                    "status": "Completed"
                }
                execution_logs.append(log_entry)

                console.print(f"[bold green]✔[/bold green] [bold cyan]{agent_name}[/bold cyan] [dim]({agent_specialty})[/dim]:")
                console.print(f"  [italic white]\"{agent_output[:200]}\"[/italic white]\n")

                previous_output = agent_output

    # Compute Merkle Root over all execution logs
    merkle_root = calculate_merkle_root(execution_logs)

    # Save comprehensive report
    if is_mesh:
        report_lines = [
            f"# {pod_name} — Mesh Swarm Execution Report",
            f"",
            f"**Task:** {user_prompt}",
            f"**Topology:** Parallel Mesh Network",
            f"**Framework:** Nous Research hermes-agent",
            f"**Model:** {model}",
            f"**Merkle Root:** `sha256:{merkle_root}`",
            f"**Timestamp:** {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}",
            f"",
            f"---",
            f"",
            f"## 💬 Swarm Communication Board Log",
            f"",
        ]
        for log in execution_logs:
            report_lines.append(f"* **{log['sender']}** ➔ **{log['recipient']}**:")
            report_lines.append(f"  > {log['content']}")
            report_lines.append("")
    else:
        report_lines = [
            f"# {pod_name} — Swarm Execution Report",
            f"",
            f"**Task:** {user_prompt}",
            f"**Topology:** Sequential Cascade",
            f"**Framework:** Nous Research hermes-agent",
            f"**Model:** {model}",
            f"**Merkle Root:** `sha256:{merkle_root}`",
            f"**Timestamp:** {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}",
            f"",
            f"---",
            f"",
        ]
        for i, log in enumerate(execution_logs):
            report_lines.append(f"## Agent {i + 1}: {log['agentName']}")
            report_lines.append(f"**Specialty:** {log['specialty']}  ")
            report_lines.append(f"**Time:** {log['timeTakenSeconds']}s  ")
            report_lines.append(f"")
            report_lines.append(f"> {log['output']}")
            report_lines.append(f"")

    report_lines.append(f"---")
    report_lines.append(f"")
    report_lines.append(f"**Consensus:** Swarm execution completed successfully.")
    report_lines.append(f"**Merkle Root Attestation:** `sha256:{merkle_root}`")

    report_content = "\n".join(report_lines)
    with open("swarm_report_local.md", "w", encoding="utf-8") as rf:
        rf.write(report_content)

    console.print(Panel(
        f"[bold bright_green]🎉 SWARM EXECUTION COMPLETE[/bold bright_green]\n\n"
        f"Logs Processed: [cyan]{len(execution_logs)}[/cyan]\n"
        f"Merkle Root: [yellow]sha256:{merkle_root[:32]}...[/yellow]\n"
        f"Report saved: [bold cyan]swarm_report_local.md[/bold cyan]",
        border_style="bright_green"
    ))


if __name__ == "__main__":
    try:
        run_hermes_swarm()
    except KeyboardInterrupt:
        console.print("\n[dim]Pipeline aborted by conductor.[/dim]")
