#!/usr/bin/env python3
"""
PodJobs - Hermes Framework Multi-Agent Swarm Orchestrator
Powered by Nous Research hermes-agent SDK (https://github.com/NousResearch/hermes-agent)

This script loads the agents_config.json generated by PodJobs and executes
each agent through the real Hermes AIAgent framework, chaining outputs
through a sequential pipeline with Merkle integrity attestation.

Prerequisites:
  pip install git+https://github.com/NousResearch/hermes-agent.git
  pip install rich requests
  
  Set one of these env vars for LLM access:
    OPENROUTER_API_KEY, OPENAI_API_KEY, ANTHROPIC_API_KEY, or GEMINI_API_KEY
"""

import json
import os
import sys
import time
import hashlib
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, TextColumn

console = Console()

# ---------------------------------------------------------------------------
# Hermes SDK Import (fail loudly if not installed)
# ---------------------------------------------------------------------------
try:
    from run_agent import AIAgent
    HERMES_AVAILABLE = True
except ImportError:
    HERMES_AVAILABLE = False
    console.print(Panel(
        "[bold red]❌ Hermes Agent SDK not installed![/bold red]\n\n"
        "Install it with:\n"
        "  [cyan]pip install git+https://github.com/NousResearch/hermes-agent.git[/cyan]\n\n"
        "Or run the auto-installer:\n"
        "  [cyan]python install_hermes.py[/cyan]",
        title="Missing Dependency",
        border_style="red"
    ))
    sys.exit(1)

# ---------------------------------------------------------------------------
# Merkle Root calculation (mirrors lib/security.ts)
# ---------------------------------------------------------------------------
def calculate_merkle_root(logs: list) -> str:
    """Compute SHA-256 Merkle root over agent execution logs."""
    if not logs:
        return hashlib.sha256(b"empty").hexdigest()
    
    leaves = []
    for log in logs:
        data = json.dumps(log, sort_keys=True).encode("utf-8")
        leaves.append(hashlib.sha256(data).hexdigest())
    
    while len(leaves) > 1:
        if len(leaves) % 2 != 0:
            leaves.append(leaves[-1])  # duplicate last leaf if odd
        next_level = []
        for i in range(0, len(leaves), 2):
            combined = (leaves[i] + leaves[i + 1]).encode("utf-8")
            next_level.append(hashlib.sha256(combined).hexdigest())
        leaves = next_level
    
    return leaves[0]

# ---------------------------------------------------------------------------
# Main Swarm Orchestrator
# ---------------------------------------------------------------------------
def run_hermes_swarm():
    # Load pod configuration generated by PodJobs
    try:
        with open("agents_config.json", "r") as f:
            config = json.load(f)
    except FileNotFoundError:
        console.print("[bold red]❌ agents_config.json not found. Generate a pod from PodJobs first.[/bold red]")
        sys.exit(1)

    pod_name = config.get("podName", "PodJobs Swarm")
    agents = config.get("agents", [])
    
    if not agents:
        console.print("[bold red]❌ No agents found in config. Generate a pod from PodJobs first.[/bold red]")
        sys.exit(1)

    # Detect LLM model — prefer free Gemini, fall back to others
    model = os.environ.get("HERMES_MODEL", "google/gemini-2.5-flash")
    
    console.print(Panel(
        f"[bold bright_green]🤖 PodJobs Hermes Swarm Orchestrator[/bold bright_green]\n"
        f"Pod: [yellow]{pod_name}[/yellow]\n"
        f"Agents: [cyan]{len(agents)}[/cyan]\n"
        f"Model: [magenta]{model}[/magenta]\n"
        f"Framework: [blue]Nous Research hermes-agent[/blue]",
        border_style="cyan"
    ))

    # Get user task
    console.print("\n[bold white]Enter task for the swarm to execute:[/bold white]")
    user_prompt = input("❯ ").strip()
    if not user_prompt:
        user_prompt = "Provide a comprehensive analysis of the current operational landscape."

    # Display agent roster
    table = Table(title=f"🗂️ {pod_name} — {len(agents)} Agents", border_style="cyan")
    table.add_column("#", justify="center", style="dim")
    table.add_column("Agent Name", style="bold green")
    table.add_column("Specialty", style="yellow")
    table.add_column("Pronouns", style="magenta")
    for i, a in enumerate(agents):
        table.add_row(str(i + 1), a.get("name", "N/A"), a.get("specialty", "N/A"), a.get("pronouns", "They/Them"))
    console.print(table)

    # Execute each agent through Hermes
    execution_logs = []
    previous_output = ""
    start_time = time.time()

    console.print(f"\n[bold yellow]⚡ Dispatching task to {len(agents)} Hermes agents...[/bold yellow]\n")

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True,
    ) as progress:

        for idx, agent_cfg in enumerate(agents):
            agent_name = agent_cfg.get("name", f"Agent {idx + 1}")
            agent_role = agent_cfg.get("role", "Operational task execution")
            agent_specialty = agent_cfg.get("specialty", "General operations")
            agent_pronouns = agent_cfg.get("pronouns", "They/Them")

            task_desc = f"[bold green][{idx + 1}/{len(agents)}][/bold green] {agent_name} ({agent_specialty})..."
            p_task = progress.add_task(description=task_desc, total=100)

            # Build system prompt from the agent's config files
            soul_md = agent_cfg.get("soulMd", "")
            safety_md = agent_cfg.get("safetyMd", "")
            
            system_context = (
                f"You are {agent_name}, an expert AI agent specializing in {agent_specialty}. "
                f"Your role: {agent_role}. Your pronouns: {agent_pronouns}. "
                f"You are agent {idx + 1} of {len(agents)} in a sequential pipeline swarm. "
                f"Be concise and technical. Max 3 sentences."
            )

            # Build the task prompt with pipeline context
            if idx == 0:
                task_prompt = f"Analyze and plan the execution for this task: \"{user_prompt}\""
            elif idx == len(agents) - 1:
                task_prompt = (
                    f"You are the Consensus Arbiter. Synthesize all pipeline outputs and "
                    f"generate a final briefing. Previous agent output: \"{previous_output[:500]}\". "
                    f"Original task: \"{user_prompt}\""
                )
            else:
                task_prompt = (
                    f"Apply your expertise in {agent_specialty} to this task: \"{user_prompt}\". "
                    f"Previous agent ({agents[idx-1].get('name', 'prior agent')}) said: "
                    f"\"{previous_output[:300]}\""
                )

            # Execute through real Hermes AIAgent
            try:
                hermes_agent = AIAgent(model=model, quiet_mode=True)
                
                # Use chat with system context
                response = hermes_agent.chat(
                    f"[System: {system_context}]\n\n{task_prompt}"
                )
                agent_output = str(response).strip() if response else f"{agent_name} completed {agent_specialty} analysis."
                
            except Exception as e:
                # If Hermes call fails (rate limit, network, etc), log the error but continue
                agent_output = f"[Hermes Error: {str(e)[:100]}] {agent_name} could not complete - pipeline continues."
                console.print(f"  [dim red]⚠ {agent_name} encountered an error: {str(e)[:80]}[/dim red]")

            progress.update(p_task, completed=100)
            elapsed = time.time() - start_time

            # Log the execution
            log_entry = {
                "agentName": agent_name,
                "role": agent_role,
                "specialty": agent_specialty,
                "output": agent_output,
                "timeTakenSeconds": round(elapsed, 1),
                "status": "Completed"
            }
            execution_logs.append(log_entry)

            console.print(f"[bold green]✔[/bold green] [bold cyan]{agent_name}[/bold cyan] [dim]({agent_specialty})[/dim]:")
            console.print(f"  [italic white]\"{agent_output[:200]}\"[/italic white]\n")

            previous_output = agent_output

    # Compute Merkle Root over all execution logs
    merkle_root = calculate_merkle_root(execution_logs)

    # Save comprehensive report
    report_lines = [
        f"# {pod_name} — Swarm Execution Report",
        f"",
        f"**Task:** {user_prompt}",
        f"**Agents Executed:** {len(execution_logs)}",
        f"**Framework:** Nous Research hermes-agent",
        f"**Model:** {model}",
        f"**Merkle Root:** `sha256:{merkle_root}`",
        f"**Timestamp:** {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}",
        f"",
        f"---",
        f"",
    ]
    for i, log in enumerate(execution_logs):
        report_lines.append(f"## Agent {i + 1}: {log['agentName']}")
        report_lines.append(f"**Specialty:** {log['specialty']}  ")
        report_lines.append(f"**Time:** {log['timeTakenSeconds']}s  ")
        report_lines.append(f"")
        report_lines.append(f"> {log['output']}")
        report_lines.append(f"")

    report_lines.append(f"---")
    report_lines.append(f"")
    report_lines.append(f"**Consensus:** All {len(execution_logs)} agents completed execution.")
    report_lines.append(f"**Merkle Root Attestation:** `sha256:{merkle_root}`")

    report_content = "\n".join(report_lines)
    with open("swarm_report_local.md", "w") as rf:
        rf.write(report_content)

    console.print(Panel(
        f"[bold bright_green]🎉 SWARM EXECUTION COMPLETE[/bold bright_green]\n\n"
        f"Agents Executed: [cyan]{len(execution_logs)}[/cyan]\n"
        f"Merkle Root: [yellow]sha256:{merkle_root[:32]}...[/yellow]\n"
        f"Report saved: [bold cyan]swarm_report_local.md[/bold cyan]",
        border_style="bright_green"
    ))


if __name__ == "__main__":
    try:
        run_hermes_swarm()
    except KeyboardInterrupt:
        console.print("\n[dim]Pipeline aborted by conductor.[/dim]")
